name: puioio
description: A smart workout logger with automated repetition counting.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  camera: ^0.10.0
  path_provider: ^2.0.11
  google_mlkit_pose_detection: ^0.4.0
  carousel_slider: ^4.1.1
  bottom_navy_bar: ^6.0.0
  dots_indicator: ^2.1.0
  lottie: ^1.4.2
  native_opencv:
    path: native_opencv
  vector_math: ^2.1.2
  flutter_launcher_icons: ^0.10.0
  percent_indicator: ^4.2.2
  stop_watch_timer: ^2.0.0
  steps_indicator: ^1.3.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/lottie/
    # - assets/test/PushUps/Pushup1/
    - assets/test/PushUps/Pushup10/
    - assets/test/PushUps/Pushup11/
    - assets/test/PushUps/Pushup12/
    - assets/test/PushUps/Pushup13/
    - assets/test/PushUps/Pushup14/
    - assets/test/PushUps/Pushup15/
    - assets/test/PushUps/Pushup16/
    - assets/test/PushUps/Pushup17/
    - assets/test/PushUps/Pushup18/
    - assets/test/PushUps/Pushup19/
    # - assets/test/PushUps/Pushup2/
    # - assets/test/PushUps/Pushup20/
    # - assets/test/PushUps/Pushup21/
    # - assets/test/PushUps/Pushup22/
    # - assets/test/PushUps/Pushup23/
    # - assets/test/PushUps/Pushup24/
    # - assets/test/PushUps/Pushup25/
    # - assets/test/PushUps/Pushup26/
    # - assets/test/PushUps/Pushup27/
    # - assets/test/PushUps/Pushup3/
    # - assets/test/PushUps/Pushup4/
    # - assets/test/PushUps/Pushup5/
    # - assets/test/PushUps/Pushup6/
    # - assets/test/PushUps/Pushup7/
    # - assets/test/PushUps/Pushup8/
    # - assets/test/PushUps/Pushup9/
    # - assets/test/PushUps/Pushup14/
    # - assets/test/PushUps/Pushup28/
    # - assets/test/PushUps/Pushup29/
    # - assets/test/PushUps/Pushup30/




flutter_icons:
  image_path: "assets/app_icon/App-icon.png"
  android: true
  ios: true
